"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"

"base_path": "."
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"

bundles:
  - 2
files:
  - source: /v3.22.0/source/english/global.ini
    translation: /v3.22.0/release/%language%/global.ini
