[package]
name = "merge_globals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
encoding_rs = "0.8.33"
encoding_rs_io = "0.1.7"
